//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRU.RTS.WS.TestClient.CarnetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", ConfigurationName="CarnetService.ICarnetService")]
    public interface ICarnetService {
        
        // CODEGEN: Parameter 'to' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://rts.iru.org/services/CarnetService-1#GetInvalidatedCarnets", ReplyAction="http://rts.iru.org/services/CarnetService-1/ICarnetService/GetInvalidatedCarnetsR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRU.RTS.WS.TestClient.CarnetService.GetInvalidatedCarnetsResponse GetInvalidatedCarnets(IRU.RTS.WS.TestClient.CarnetService.GetInvalidatedCarnetsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rts.iru.org/model/carnet-1")]
    public partial class stoppedCarnetsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stoppedCarnetsTypeTotal totalField;
        
        private stoppedCarnetsTypeStoppedCarnets stoppedCarnetsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public stoppedCarnetsTypeTotal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public stoppedCarnetsTypeStoppedCarnets StoppedCarnets {
            get {
                return this.stoppedCarnetsField;
            }
            set {
                this.stoppedCarnetsField = value;
                this.RaisePropertyChanged("StoppedCarnets");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rts.iru.org/model/carnet-1")]
    public partial class stoppedCarnetsTypeTotal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rts.iru.org/model/carnet-1")]
    public partial class stoppedCarnetType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string carnetNumberField;
        
        private System.DateTime expiryDateField;
        
        private string associationField;
        
        private string holderField;
        
        private System.DateTime declarationDateField;
        
        private System.DateTime invalidationDateField;
        
        private invalidationStatusType invalidationStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string CarnetNumber {
            get {
                return this.carnetNumberField;
            }
            set {
                this.carnetNumberField = value;
                this.RaisePropertyChanged("CarnetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("ExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Association {
            get {
                return this.associationField;
            }
            set {
                this.associationField = value;
                this.RaisePropertyChanged("Association");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Holder {
            get {
                return this.holderField;
            }
            set {
                this.holderField = value;
                this.RaisePropertyChanged("Holder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime DeclarationDate {
            get {
                return this.declarationDateField;
            }
            set {
                this.declarationDateField = value;
                this.RaisePropertyChanged("DeclarationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime InvalidationDate {
            get {
                return this.invalidationDateField;
            }
            set {
                this.invalidationDateField = value;
                this.RaisePropertyChanged("InvalidationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public invalidationStatusType InvalidationStatus {
            get {
                return this.invalidationStatusField;
            }
            set {
                this.invalidationStatusField = value;
                this.RaisePropertyChanged("InvalidationStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rts.iru.org/model/carnet-1")]
    public enum invalidationStatusType {
        
        /// <remarks/>
        Destroyed,
        
        /// <remarks/>
        Lost,
        
        /// <remarks/>
        Stolen,
        
        /// <remarks/>
        Retained,
        
        /// <remarks/>
        Excluded,
        
        /// <remarks/>
        Invalidated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rts.iru.org/model/carnet-1")]
    public partial class stoppedCarnetsTypeStoppedCarnets : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stoppedCarnetType[] stoppedCarnetField;
        
        private int offsetField;
        
        private int countField;
        
        private bool endReachedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StoppedCarnet", Order=0)]
        public stoppedCarnetType[] StoppedCarnet {
            get {
                return this.stoppedCarnetField;
            }
            set {
                this.stoppedCarnetField = value;
                this.RaisePropertyChanged("StoppedCarnet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("Offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EndReached {
            get {
                return this.endReachedField;
            }
            set {
                this.endReachedField = value;
                this.RaisePropertyChanged("EndReached");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvalidatedCarnets", WrapperNamespace="http://rts.iru.org/services/CarnetService-1", IsWrapped=true)]
    public partial class GetInvalidatedCarnetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=0)]
        public System.DateTime from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> offset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> count;
        
        public GetInvalidatedCarnetsRequest() {
        }
        
        public GetInvalidatedCarnetsRequest(System.DateTime from, System.Nullable<System.DateTime> to, System.Nullable<int> offset, System.Nullable<int> count) {
            this.from = from;
            this.to = to;
            this.offset = offset;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvalidatedCarnetsResponse", WrapperNamespace="http://rts.iru.org/services/CarnetService-1", IsWrapped=true)]
    public partial class GetInvalidatedCarnetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=0)]
        public IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsType GetInvalidatedCarnetsResult;
        
        public GetInvalidatedCarnetsResponse() {
        }
        
        public GetInvalidatedCarnetsResponse(IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsType GetInvalidatedCarnetsResult) {
            this.GetInvalidatedCarnetsResult = GetInvalidatedCarnetsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICarnetServiceChannel : IRU.RTS.WS.TestClient.CarnetService.ICarnetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CarnetServiceClient : System.ServiceModel.ClientBase<IRU.RTS.WS.TestClient.CarnetService.ICarnetService>, IRU.RTS.WS.TestClient.CarnetService.ICarnetService {
        
        public CarnetServiceClient() {
        }
        
        public CarnetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarnetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarnetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarnetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRU.RTS.WS.TestClient.CarnetService.GetInvalidatedCarnetsResponse IRU.RTS.WS.TestClient.CarnetService.ICarnetService.GetInvalidatedCarnets(IRU.RTS.WS.TestClient.CarnetService.GetInvalidatedCarnetsRequest request) {
            return base.Channel.GetInvalidatedCarnets(request);
        }
        
        public IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsType GetInvalidatedCarnets(System.DateTime from, System.Nullable<System.DateTime> to, System.Nullable<int> offset, System.Nullable<int> count) {
            IRU.RTS.WS.TestClient.CarnetService.GetInvalidatedCarnetsRequest inValue = new IRU.RTS.WS.TestClient.CarnetService.GetInvalidatedCarnetsRequest();
            inValue.from = from;
            inValue.to = to;
            inValue.offset = offset;
            inValue.count = count;
            IRU.RTS.WS.TestClient.CarnetService.GetInvalidatedCarnetsResponse retVal = ((IRU.RTS.WS.TestClient.CarnetService.ICarnetService)(this)).GetInvalidatedCarnets(inValue);
            return retVal.GetInvalidatedCarnetsResult;
        }
    }
}
