//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRU.RTS.WS.TestClient.CarnetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", ConfigurationName="CarnetService.ICarnetServiceSEI")]
    public interface ICarnetServiceSEI {
        
        // CODEGEN: Generating message contract since message part namespace (http://rts.iru.org/model/carnet-1) does not match the default value (http://rts.iru.org/services/CarnetService-1)
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://rts.iru.org/services/CarnetService-1/queryCarnet", ReplyAction="http://rts.iru.org/services/CarnetService-1/queryCarnetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarnetBaseType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TIRCarnet")]
        IRU.RTS.WS.TestClient.CarnetService.queryCarnetResponse queryCarnet(IRU.RTS.WS.TestClient.CarnetService.queryCarnetRequest request);
        
        // CODEGEN: Parameter 'to' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://rts.iru.org/services/CarnetService-1/getStoppedCarnets", ReplyAction="http://rts.iru.org/services/CarnetService-1/getStoppedCarnetsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarnetBaseType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="total")]
        IRU.RTS.WS.TestClient.CarnetService.getStoppedCarnetsResponse getStoppedCarnets(IRU.RTS.WS.TestClient.CarnetService.getStoppedCarnetsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rts.iru.org/model/carnet-1")]
    public partial class CarnetType : CarnetBaseType {
        
        private CarnetStatusType statusField;
        
        private CarnetTypeTIROperationTerminations tIROperationTerminationsField;
        
        private string voucherNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CarnetStatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CarnetTypeTIROperationTerminations TIROperationTerminations {
            get {
                return this.tIROperationTerminationsField;
            }
            set {
                this.tIROperationTerminationsField = value;
                this.RaisePropertyChanged("TIROperationTerminations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VoucherNumber {
            get {
                return this.voucherNumberField;
            }
            set {
                this.voucherNumberField = value;
                this.RaisePropertyChanged("VoucherNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rts.iru.org/model/carnet-1")]
    public enum CarnetStatusType {
        
        /// <remarks/>
        ISSUED_TO_ASSOCIATION,
        
        /// <remarks/>
        ISSUED_TO_HAULIER,
        
        /// <remarks/>
        RETURNED_TO_ASSOCIATION,
        
        /// <remarks/>
        RETURNED_TO_IRU,
        
        /// <remarks/>
        STOPPED,
        
        /// <remarks/>
        INCORRECT_NUMBER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rts.iru.org/model/carnet-1")]
    public partial class CarnetTypeTIROperationTerminations : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint countField;
        
        private bool hasFinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool hasFinal {
            get {
                return this.hasFinalField;
            }
            set {
                this.hasFinalField = value;
                this.RaisePropertyChanged("hasFinal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org/model/tir-actor-1")]
    public partial class HaulierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StoppedCarnetType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CarnetType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rts.iru.org/model/carnet-1")]
    public partial class CarnetBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tIRCarnetNumberField;
        
        private System.DateTime expiryDateField;
        
        private Association associationField;
        
        private HaulierType holderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string TIRCarnetNumber {
            get {
                return this.tIRCarnetNumberField;
            }
            set {
                this.tIRCarnetNumberField = value;
                this.RaisePropertyChanged("TIRCarnetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("ExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.iru.org/model/tir-actor-1", Order=2)]
        public Association Association {
            get {
                return this.associationField;
            }
            set {
                this.associationField = value;
                this.RaisePropertyChanged("Association");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.iru.org/model/tir-actor-1", Order=3)]
        public HaulierType Holder {
            get {
                return this.holderField;
            }
            set {
                this.holderField = value;
                this.RaisePropertyChanged("Holder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.iru.org/model/tir-actor-1")]
    public partial class Association : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rts.iru.org/model/carnet-1")]
    public partial class StoppedCarnetType : CarnetBaseType {
        
        private System.DateTime declarationDateField;
        
        private System.DateTime invalidationDateField;
        
        private InvalidationStatusType invalidationStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DeclarationDate {
            get {
                return this.declarationDateField;
            }
            set {
                this.declarationDateField = value;
                this.RaisePropertyChanged("DeclarationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime InvalidationDate {
            get {
                return this.invalidationDateField;
            }
            set {
                this.invalidationDateField = value;
                this.RaisePropertyChanged("InvalidationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public InvalidationStatusType InvalidationStatus {
            get {
                return this.invalidationStatusField;
            }
            set {
                this.invalidationStatusField = value;
                this.RaisePropertyChanged("InvalidationStatus");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rts.iru.org/model/carnet-1")]
    public enum InvalidationStatusType {
        
        /// <remarks/>
        DESTROYED,
        
        /// <remarks/>
        LOST,
        
        /// <remarks/>
        STOLEN,
        
        /// <remarks/>
        RETAINED,
        
        /// <remarks/>
        EXCLUDED,
        
        /// <remarks/>
        INVALIDATED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryCarnet", WrapperNamespace="http://rts.iru.org/services/CarnetService-1", IsWrapped=true)]
    public partial class queryCarnetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/model/carnet-1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string TIRCarnetNumber;
        
        public queryCarnetRequest() {
        }
        
        public queryCarnetRequest(string TIRCarnetNumber) {
            this.TIRCarnetNumber = TIRCarnetNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryCarnetResponse", WrapperNamespace="http://rts.iru.org/services/CarnetService-1", IsWrapped=true)]
    public partial class queryCarnetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=0)]
        public IRU.RTS.WS.TestClient.CarnetService.CarnetType TIRCarnet;
        
        public queryCarnetResponse() {
        }
        
        public queryCarnetResponse(IRU.RTS.WS.TestClient.CarnetService.CarnetType TIRCarnet) {
            this.TIRCarnet = TIRCarnet;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rts.iru.org/services/CarnetService-1")]
    public partial class stoppedCarnetsTypeTotal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromField;
        
        private bool fromFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromSpecified {
            get {
                return this.fromFieldSpecified;
            }
            set {
                this.fromFieldSpecified = value;
                this.RaisePropertyChanged("fromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
                this.RaisePropertyChanged("toSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rts.iru.org/services/CarnetService-1")]
    public partial class stoppedCarnetsTypeStoppedCarnets : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StoppedCarnetType[] stoppedCarnetField;
        
        private int offsetField;
        
        private int countField;
        
        private bool endReachedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StoppedCarnet", Order=0)]
        public StoppedCarnetType[] StoppedCarnet {
            get {
                return this.stoppedCarnetField;
            }
            set {
                this.stoppedCarnetField = value;
                this.RaisePropertyChanged("StoppedCarnet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool endReached {
            get {
                return this.endReachedField;
            }
            set {
                this.endReachedField = value;
                this.RaisePropertyChanged("endReached");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStoppedCarnets", WrapperNamespace="http://rts.iru.org/services/CarnetService-1", IsWrapped=true)]
    public partial class getStoppedCarnetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=0)]
        public System.DateTime from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> offset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<uint> maxCount;
        
        public getStoppedCarnetsRequest() {
        }
        
        public getStoppedCarnetsRequest(System.DateTime from, System.Nullable<System.DateTime> to, System.Nullable<int> offset, System.Nullable<uint> maxCount) {
            this.from = from;
            this.to = to;
            this.offset = offset;
            this.maxCount = maxCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStoppedCarnetsResponse", WrapperNamespace="http://rts.iru.org/services/CarnetService-1", IsWrapped=true)]
    public partial class getStoppedCarnetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=0)]
        public IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsTypeTotal total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/services/CarnetService-1", Order=1)]
        public IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsTypeStoppedCarnets stoppedCarnets;
        
        public getStoppedCarnetsResponse() {
        }
        
        public getStoppedCarnetsResponse(IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsTypeTotal total, IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsTypeStoppedCarnets stoppedCarnets) {
            this.total = total;
            this.stoppedCarnets = stoppedCarnets;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICarnetServiceSEIChannel : IRU.RTS.WS.TestClient.CarnetService.ICarnetServiceSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CarnetServiceSEIClient : System.ServiceModel.ClientBase<IRU.RTS.WS.TestClient.CarnetService.ICarnetServiceSEI>, IRU.RTS.WS.TestClient.CarnetService.ICarnetServiceSEI {
        
        public CarnetServiceSEIClient() {
        }
        
        public CarnetServiceSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarnetServiceSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarnetServiceSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarnetServiceSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRU.RTS.WS.TestClient.CarnetService.queryCarnetResponse IRU.RTS.WS.TestClient.CarnetService.ICarnetServiceSEI.queryCarnet(IRU.RTS.WS.TestClient.CarnetService.queryCarnetRequest request) {
            return base.Channel.queryCarnet(request);
        }
        
        public IRU.RTS.WS.TestClient.CarnetService.CarnetType queryCarnet(string TIRCarnetNumber) {
            IRU.RTS.WS.TestClient.CarnetService.queryCarnetRequest inValue = new IRU.RTS.WS.TestClient.CarnetService.queryCarnetRequest();
            inValue.TIRCarnetNumber = TIRCarnetNumber;
            IRU.RTS.WS.TestClient.CarnetService.queryCarnetResponse retVal = ((IRU.RTS.WS.TestClient.CarnetService.ICarnetServiceSEI)(this)).queryCarnet(inValue);
            return retVal.TIRCarnet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRU.RTS.WS.TestClient.CarnetService.getStoppedCarnetsResponse IRU.RTS.WS.TestClient.CarnetService.ICarnetServiceSEI.getStoppedCarnets(IRU.RTS.WS.TestClient.CarnetService.getStoppedCarnetsRequest request) {
            return base.Channel.getStoppedCarnets(request);
        }
        
        public IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsTypeTotal getStoppedCarnets(System.DateTime from, System.Nullable<System.DateTime> to, System.Nullable<int> offset, System.Nullable<uint> maxCount, out IRU.RTS.WS.TestClient.CarnetService.stoppedCarnetsTypeStoppedCarnets stoppedCarnets) {
            IRU.RTS.WS.TestClient.CarnetService.getStoppedCarnetsRequest inValue = new IRU.RTS.WS.TestClient.CarnetService.getStoppedCarnetsRequest();
            inValue.from = from;
            inValue.to = to;
            inValue.offset = offset;
            inValue.maxCount = maxCount;
            IRU.RTS.WS.TestClient.CarnetService.getStoppedCarnetsResponse retVal = ((IRU.RTS.WS.TestClient.CarnetService.ICarnetServiceSEI)(this)).getStoppedCarnets(inValue);
            stoppedCarnets = retVal.stoppedCarnets;
            return retVal.total;
        }
    }
}
