//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591

namespace RTSTestClient.TIREPDG2B {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIREPDG2BServiceClassSoap", Namespace="http://www.iru.org")]
    public partial class TIREPDG2BService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TIREPDG2BOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TIREPDG2BService() {
            this.Url = global::RTSTestClient.Properties.Settings.Default.RTSTestClient_TIREPDG2B_TIREPDG2BService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TIREPDG2BCompletedEventHandler TIREPDG2BCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.iru.org/TIREPDG2B", RequestNamespace="http://www.iru.org", ResponseNamespace="http://www.iru.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIREPDG2BUploadAck TIREPDG2B(TIREPDG2BUploadParams su) {
            object[] results = this.Invoke("TIREPDG2B", new object[] {
                        su});
            return ((TIREPDG2BUploadAck)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTIREPDG2B(TIREPDG2BUploadParams su, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TIREPDG2B", new object[] {
                        su}, callback, asyncState);
        }
        
        /// <remarks/>
        public TIREPDG2BUploadAck EndTIREPDG2B(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TIREPDG2BUploadAck)(results[0]));
        }
        
        /// <remarks/>
        public void TIREPDG2BAsync(TIREPDG2BUploadParams su) {
            this.TIREPDG2BAsync(su, null);
        }
        
        /// <remarks/>
        public void TIREPDG2BAsync(TIREPDG2BUploadParams su, object userState) {
            if ((this.TIREPDG2BOperationCompleted == null)) {
                this.TIREPDG2BOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTIREPDG2BOperationCompleted);
            }
            this.InvokeAsync("TIREPDG2B", new object[] {
                        su}, this.TIREPDG2BOperationCompleted, userState);
        }
        
        private void OnTIREPDG2BOperationCompleted(object arg) {
            if ((this.TIREPDG2BCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TIREPDG2BCompleted(this, new TIREPDG2BCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
    public partial class TIREPDG2BUploadParams {
        
        private string subscriberIDField;
        
        private string certificateIDField;
        
        private byte[] eSessionKeyField;
        
        private string subscriberMessageIDField;
        
        private string informationExchangeVersionField;
        
        private string messageNameField;
        
        private System.DateTime timeSentField;
        
        private byte[] messageContentField;
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        public string CertificateID {
            get {
                return this.certificateIDField;
            }
            set {
                this.certificateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ESessionKey {
            get {
                return this.eSessionKeyField;
            }
            set {
                this.eSessionKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriberMessageID {
            get {
                return this.subscriberMessageIDField;
            }
            set {
                this.subscriberMessageIDField = value;
            }
        }
        
        /// <remarks/>
        public string InformationExchangeVersion {
            get {
                return this.informationExchangeVersionField;
            }
            set {
                this.informationExchangeVersionField = value;
            }
        }
        
        /// <remarks/>
        public string MessageName {
            get {
                return this.messageNameField;
            }
            set {
                this.messageNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeSent {
            get {
                return this.timeSentField;
            }
            set {
                this.timeSentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MessageContent {
            get {
                return this.messageContentField;
            }
            set {
                this.messageContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
    public partial class TIREPDG2BUploadAck {
        
        private string hostIDField;
        
        private string subscriberMessageIDField;
        
        private int returnCodeField;
        
        private int returnCodeReasonField;
        
        /// <remarks/>
        public string HostID {
            get {
                return this.hostIDField;
            }
            set {
                this.hostIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriberMessageID {
            get {
                return this.subscriberMessageIDField;
            }
            set {
                this.subscriberMessageIDField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnCodeReason {
            get {
                return this.returnCodeReasonField;
            }
            set {
                this.returnCodeReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TIREPDG2BCompletedEventHandler(object sender, TIREPDG2BCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIREPDG2BCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TIREPDG2BCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIREPDG2BUploadAck Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIREPDG2BUploadAck)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591