//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRU.RTS.TIREPD.B2G.CipherHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<soap:Envelope xmlns:soap=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <soap:Body>
    <TIREPDB2G xmlns=""http://www.iru.org"">
      <su>
        <SubscriberID></SubscriberID>
        <CertificateID></CertificateID>
        <ESessionKey></ESessionKey>
        <SubscriberMessageID></SubscriberMessageID>
        <InformationExchangeVersion></InformationExchangeVersion>
        <MessageName></MessageName>
        <TimeSent></TimeSent>
        <MessageContent></MessageContent>
      </su>
    </TIREPDB2G>
  </soap:Body>
</soap:Envelope>")]
        public string Empty2BGRequest {
            get {
                return ((string)(this["Empty2BGRequest"]));
            }
        }
    }
}
