//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace WSCscc_Client.WSSTstc {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SafeTIRUploadCopyServiceSoap", Namespace="http://www.iru.org")]
    public class SafeTIRUploadCopyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SafeTIRUploadCopyService() {
            this.Url = "http://localhost/RTS/WSSTstc_WS/asmapCopy.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.iru.org/WSSTstc", RequestNamespace="http://www.iru.org", ResponseNamespace="http://www.iru.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SafeTIRUploadCopyAck WSSTstc(SafeTIRUploadCopy su) {
            object[] results = this.Invoke("WSSTstc", new object[] {
                        su});
            return ((SafeTIRUploadCopyAck)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWSSTstc(SafeTIRUploadCopy su, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WSSTstc", new object[] {
                        su}, callback, asyncState);
        }
        
        /// <remarks/>
        public SafeTIRUploadCopyAck EndWSSTstc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SafeTIRUploadCopyAck)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
    public class SafeTIRUploadCopy {
        
        /// <remarks/>
        public string MessageTag;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public System.Byte[] ESessionKey;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public System.Byte[] safeTIRUploadData;
        
        /// <remarks/>
        public string CopyToID;
        
        /// <remarks/>
        public string CopyFromID;
        
        /// <remarks/>
        public string Sender_MessageID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
    public class SafeTIRUploadCopyAck {
        
        /// <remarks/>
        public int ReturnCode;
    }
}
