//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using IRU.RTS.TIREPD;
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Web.Services.WebServiceBindingAttribute(Name="TIREPDB2GServiceClassSoap", Namespace="http://www.iru.org")]
public interface ITIREPDB2GServiceClassSoap {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.iru.org/TIREPDB2G", RequestNamespace="http://www.iru.org", ResponseNamespace="http://www.iru.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    TIREPDB2GUploadAck TIREPDB2G(TIREPDB2GUploadParams su);
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
//public partial class TIREPDB2GUploadParams {
    
//    private string subscriberIDField;
    
//    private string certificateIDField;
    
//    private byte[] eSessionKeyField;
    
//    private string subscriberMessageIDField;
    
//    private string informationExchangeVersionField;
    
//    private string messageNameField;
    
//    private System.DateTime timeSentField;
    
//    private byte[] messageContentField;
    
//    /// <remarks/>
//    public string SubscriberID {
//        get {
//            return this.subscriberIDField;
//        }
//        set {
//            this.subscriberIDField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string CertificateID {
//        get {
//            return this.certificateIDField;
//        }
//        set {
//            this.certificateIDField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] ESessionKey {
//        get {
//            return this.eSessionKeyField;
//        }
//        set {
//            this.eSessionKeyField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string SubscriberMessageID {
//        get {
//            return this.subscriberMessageIDField;
//        }
//        set {
//            this.subscriberMessageIDField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string InformationExchangeVersion {
//        get {
//            return this.informationExchangeVersionField;
//        }
//        set {
//            this.informationExchangeVersionField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string MessageName {
//        get {
//            return this.messageNameField;
//        }
//        set {
//            this.messageNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    public System.DateTime TimeSent {
//        get {
//            return this.timeSentField;
//        }
//        set {
//            this.timeSentField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] MessageContent {
//        get {
//            return this.messageContentField;
//        }
//        set {
//            this.messageContentField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
//public partial class TIREPDB2GUploadAck {
    
//    private string hostIDField;
    
//    private string subscriberMessageIDField;
    
//    private int returnCodeField;
    
//    private int returnCodeReasonField;
    
//    /// <remarks/>
//    public string HostID {
//        get {
//            return this.hostIDField;
//        }
//        set {
//            this.hostIDField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string SubscriberMessageID {
//        get {
//            return this.subscriberMessageIDField;
//        }
//        set {
//            this.subscriberMessageIDField = value;
//        }
//    }
    
//    /// <remarks/>
//    public int ReturnCode {
//        get {
//            return this.returnCodeField;
//        }
//        set {
//            this.returnCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public int ReturnCodeReason {
//        get {
//            return this.returnCodeReasonField;
//        }
//        set {
//            this.returnCodeReasonField = value;
//        }
//    }
//}
