//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://epd.iru.org/services/TransitMessagingService-1", ConfigurationName="BizTalk.eTIR.TransitMessagingService.IRU_EPD_BizTalk_eTIR_Orchestrations_services" +
        "_TransitMessagingService_1_TransitMessagingSEIPort")]
    public interface IRU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPort {
        
        // CODEGEN: Generating message contract since the operation getTransitMessagesOfGuarantee is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getTransitMessagesOfGuarantee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeResponse1 getTransitMessagesOfGuarantee(IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://epd.iru.org/services/TransitMessagingService-1")]
    public partial class getTransitMessagesOfGuarantee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guaranteeNumberField;
        
        private string[] countriesField;
        
        private int[] messageTypesField;
        
        private getTransitMessagesOfGuaranteeOriginalMessageDatetime originalMessageDatetimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GuaranteeNumber {
            get {
                return this.guaranteeNumberField;
            }
            set {
                this.guaranteeNumberField = value;
                this.RaisePropertyChanged("GuaranteeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CountryCode", IsNullable=false)]
        public string[] Countries {
            get {
                return this.countriesField;
            }
            set {
                this.countriesField = value;
                this.RaisePropertyChanged("Countries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageTypeId", IsNullable=false)]
        public int[] MessageTypes {
            get {
                return this.messageTypesField;
            }
            set {
                this.messageTypesField = value;
                this.RaisePropertyChanged("MessageTypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public getTransitMessagesOfGuaranteeOriginalMessageDatetime OriginalMessageDatetime {
            get {
                return this.originalMessageDatetimeField;
            }
            set {
                this.originalMessageDatetimeField = value;
                this.RaisePropertyChanged("OriginalMessageDatetime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://epd.iru.org/services/TransitMessagingService-1")]
    public partial class getTransitMessagesOfGuaranteeOriginalMessageDatetime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromField;
        
        private bool fromFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromSpecified {
            get {
                return this.fromFieldSpecified;
            }
            set {
                this.fromFieldSpecified = value;
                this.RaisePropertyChanged("FromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
                this.RaisePropertyChanged("ToSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://epd.iru.org/model/TransitMessaging-1")]
    public partial class TransitMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iruReferenceNumberField;
        
        private string countryCodeField;
        
        private int messageTypeIdField;
        
        private string guaranteeNumberField;
        
        private System.DateTime originalProcessedDatetimeField;
        
        private string messageXmlField;
        
        private System.DateTime lAST_UPDATE_DATETIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IruReferenceNumber {
            get {
                return this.iruReferenceNumberField;
            }
            set {
                this.iruReferenceNumberField = value;
                this.RaisePropertyChanged("IruReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MessageTypeId {
            get {
                return this.messageTypeIdField;
            }
            set {
                this.messageTypeIdField = value;
                this.RaisePropertyChanged("MessageTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GuaranteeNumber {
            get {
                return this.guaranteeNumberField;
            }
            set {
                this.guaranteeNumberField = value;
                this.RaisePropertyChanged("GuaranteeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime OriginalProcessedDatetime {
            get {
                return this.originalProcessedDatetimeField;
            }
            set {
                this.originalProcessedDatetimeField = value;
                this.RaisePropertyChanged("OriginalProcessedDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MessageXml {
            get {
                return this.messageXmlField;
            }
            set {
                this.messageXmlField = value;
                this.RaisePropertyChanged("MessageXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime LAST_UPDATE_DATETIME {
            get {
                return this.lAST_UPDATE_DATETIMEField;
            }
            set {
                this.lAST_UPDATE_DATETIMEField = value;
                this.RaisePropertyChanged("LAST_UPDATE_DATETIME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://epd.iru.org/services/TransitMessagingService-1")]
    public partial class getTransitMessagesOfGuaranteeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransitMessageType[] getTransitMessagesOfGuaranteeResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TransitMessage", Namespace="http://epd.iru.org/model/TransitMessaging-1", IsNullable=false)]
        public TransitMessageType[] GetTransitMessagesOfGuaranteeResult {
            get {
                return this.getTransitMessagesOfGuaranteeResultField;
            }
            set {
                this.getTransitMessagesOfGuaranteeResultField = value;
                this.RaisePropertyChanged("GetTransitMessagesOfGuaranteeResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransitMessagesOfGuaranteeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://epd.iru.org/services/TransitMessagingService-1", Order=0)]
        public IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuarantee getTransitMessagesOfGuarantee;
        
        public getTransitMessagesOfGuaranteeRequest() {
        }
        
        public getTransitMessagesOfGuaranteeRequest(IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuarantee getTransitMessagesOfGuarantee) {
            this.getTransitMessagesOfGuarantee = getTransitMessagesOfGuarantee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransitMessagesOfGuaranteeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://epd.iru.org/services/TransitMessagingService-1", Order=0)]
        public IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeResponse getTransitMessagesOfGuaranteeResponse;
        
        public getTransitMessagesOfGuaranteeResponse1() {
        }
        
        public getTransitMessagesOfGuaranteeResponse1(IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeResponse getTransitMessagesOfGuaranteeResponse) {
            this.getTransitMessagesOfGuaranteeResponse = getTransitMessagesOfGuaranteeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IRU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPortChannel : IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.IRU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPortClient : System.ServiceModel.ClientBase<IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.IRU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPort>, IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.IRU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPort {
        
        public RU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPortClient() {
        }
        
        public RU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeResponse1 IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.IRU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPort.getTransitMessagesOfGuarantee(IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeRequest request) {
            return base.Channel.getTransitMessagesOfGuarantee(request);
        }
        
        public IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeResponse getTransitMessagesOfGuarantee(IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuarantee getTransitMessagesOfGuarantee1) {
            IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeRequest inValue = new IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeRequest();
            inValue.getTransitMessagesOfGuarantee = getTransitMessagesOfGuarantee1;
            IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.getTransitMessagesOfGuaranteeResponse1 retVal = ((IRU.RTS.WSEGIS.BizTalk.eTIR.TransitMessagingService.IRU_EPD_BizTalk_eTIR_Orchestrations_services_TransitMessagingService_1_TransitMessagingSEIPort)(this)).getTransitMessagesOfGuarantee(inValue);
            return retVal.getTransitMessagesOfGuaranteeResponse;
        }
    }
}
