/****** Object:  Schema [egis]    Script Date: 02/20/2015 16:51:19 ******/
CREATE SCHEMA [egis]
GO
/****** Object:  Table [egis].[STEP_RESULT_DEFINITIONS]    Script Date: 02/20/2015 16:51:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [egis].[STEP_RESULT_DEFINITIONS](
	[STEP] [int] NOT NULL,
	[STEP_RESULT] [int] NOT NULL,
	[STEP_RESULT_DESCRIPTION] [nvarchar](255) NOT NULL,
 CONSTRAINT [EGIS_STEP_RESULT_DEFINITIONS_PK] PRIMARY KEY CLUSTERED 
(
	[STEP] ASC,
	[STEP_RESULT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (5, 1, N'ok')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (5, 1200, N'Unclassified Error')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (5, 1211, N'No Keys corresponding MessageTag')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (5, 1212, N'Empty/UnRegistered Subscriber ID')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (5, 1213, N'Empty ESessionKey')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (5, 1214, N'TIRCarnetHolderQueryParams')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (10, 1, N'ok')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (10, 3, N'Key Discarded/Deactivated')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (10, 4, N'Invalid Method')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (10, 7, N'SubscriberIDs in the header and Message do not match')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (10, 8, N'Decryption Failure/Exception')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (10, 9, N'No Key Found')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (15, 1, N'ok')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (15, 8, N'Message Decryption Failure/Exception')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (20, 1, N'ok')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (20, 7, N'Hash Mismatch')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (20, 8, N'Hash Failure/Exception')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (25, 1, N'ok')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (25, 1234, N'Worng Query Time Format')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (25, 1236, N'Originator Code Missing or in wrong Format')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (25, 1237, N'Origin time in Wrong format')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (25, 1239, N'Query Type not specified or wrong value')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (25, 1240, N'Query Type not specified or wrong value')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (25, 1241, N'TIR Carnet not specified or wrong format ')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (30, 1, N'ok')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (30, 2, N'Sender Not Found')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (30, 3, N'Sender Found but invalid password')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (35, 1, N'ok')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (35, 2, N'CuteWise Query Exception ')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (45, 1, N'ok')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (45, 8, N'Session Key Encryption Failure / Exception')
INSERT [egis].[STEP_RESULT_DEFINITIONS] ([STEP], [STEP_RESULT], [STEP_RESULT_DESCRIPTION]) VALUES (99, 2, N'Final Ok')
/****** Object:  Table [egis].[STEP_DEFINITIONS]    Script Date: 02/20/2015 16:51:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [egis].[STEP_DEFINITIONS](
	[STEP] [int] NOT NULL,
	[STEP_DESCRIPTION] [nvarchar](255) NOT NULL,
 CONSTRAINT [EGIS_STEP_DEFINITIONS_PK] PRIMARY KEY CLUSTERED 
(
	[STEP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (5, N'Log initial Request And Validate Parameters')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (10, N'Session Key Decryption')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (15, N'Query Params Decryption')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (20, N'Validate Hash')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (25, N'Query XML Validation')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (30, N'Sender Authentication')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (35, N'CW Data Query')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (40, N'Hash & encrypt Response')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (45, N'Encrypt Session Key')
INSERT [egis].[STEP_DEFINITIONS] ([STEP], [STEP_DESCRIPTION]) VALUES (99, N'Final')
/****** Object:  Table [egis].[RTS_IDS]    Script Date: 02/20/2015 16:51:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [egis].[RTS_IDS](
	[ID_PURPOSE] [nvarchar](50) NOT NULL,
	[ID_VALUE] [numeric](10, 0) NOT NULL,
	[ID_DESCRIPTION] [nvarchar](500) NULL,
 CONSTRAINT [RTS_IDS_PK] PRIMARY KEY CLUSTERED 
(
	[ID_PURPOSE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [egis].[RTS_IDS] ([ID_PURPOSE], [ID_VALUE], [ID_DESCRIPTION]) VALUES (N'EGIS_Query_ID', CAST(0 AS Numeric(10, 0)), N'Last EGIS Query Id generated')
/****** Object:  Table [egis].[EGIS_SEQUENCE]    Script Date: 02/20/2015 16:51:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [egis].[EGIS_SEQUENCE](
	[EGIS_QUERY_ID] [numeric](10, 0) NOT NULL,
	[EGIS_STEP] [int] NOT NULL,
	[EGIS_STEP_RESULT] [int] NOT NULL,
	[EGIS_STEP_ERROR_DESC] [ntext] NULL,
	[LAST_UPDATE_TIME] [datetime] NOT NULL,
 CONSTRAINT [EGIS_SEQUENCE_PK] PRIMARY KEY CLUSTERED 
(
	[EGIS_QUERY_ID] ASC,
	[EGIS_STEP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [egis].[EGIS_REQUEST_LOG]    Script Date: 02/20/2015 16:51:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [egis].[EGIS_REQUEST_LOG](
	[EGIS_QUERY_ID] [numeric](10, 0) NOT NULL,
	[DECRYPTION_KEY_ID] [varchar](255) NULL,
	[ENCRYPTED_QUERY_PARAMS] [image] NULL,
	[SENDER_TCP_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[QUERY_PARAM_OK] [int] NULL,
	[DECRYPTION_RESULT] [int] NULL,
	[DECRYPTION_RESULT_DESCRIPTION] [nvarchar](800) NULL,
	[QUERY_XML] [ntext] NULL,
	[SESSION_KEY_USED_ENCRYPTED_IN] [image] NULL,
	[SESSION_KEY_USED_DECRYPTED_IN] [image] NULL,
	[QUERY_XML_VALID] [int] NULL,
	[QUERY_XML_INVALID_REASON] [nvarchar](800) NULL,
	[SENDER_ID] [nvarchar](255) NULL,
	[ORIGINATOR] [nvarchar](30) NULL,
	[ORIGIN_TIME] [datetime] NULL,
	[SENDER_PASSWORD] [nvarchar](255) NULL,
	[QUERY_TYPE] [int] NULL,
	[CARNET_NUMBER] [nvarchar](12) NULL,
	[SENDER_QUERY_ID] [nvarchar](255) NULL,
	[SENDER_AUTHENTICATED] [int] NULL,
	[RETURN_CODE] [int] NULL,
	[QUERY_RESULT_CODE] [int] NULL,
	[HOLDER_ID] [nvarchar](60) NULL,
	[VALIDITY_DATE] [datetime] NULL,
	[ASSOCIATION_SHORT_NAME] [nvarchar](255) NULL,
	[NUMBER_TERMINATIONS] [int] NULL,
	[RESPONSE_ENCRYPTION_RESULT] [int] NULL,
	[RESPONSE_ENCRYPTION_RESULT_DESCRIPTION] [nvarchar](800) NULL,
	[SESSION_KEY_USED_ENCRYPTED_OUT] [image] NULL,
	[SESSION_KEY_USED_DECRYPTED_OUT] [image] NULL,
	[SESSION_KEY_ENCRYPTION_KEY_ID_USED] [varchar](255) NULL,
	[RESPONSE_RESULT] [int] NULL,
	[RESPONSE_TIME] [datetime] NULL,
	[ROW_CREATED_TIME] [datetime] NOT NULL,
	[LAST_STEP] [int] NULL,
	[COMPLETION_TIME] [datetime] NULL,
	[VOUCHER_NUMBER] [varchar](14) NULL,
	[RESPONSE_XML] [xml] NULL,
 CONSTRAINT [EGIS_REQUEST_LOG_PK] PRIMARY KEY CLUSTERED 
(
	[EGIS_QUERY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO