//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5472.
// 
#pragma warning disable 1591

namespace RTSTestClient.Query {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SafeTIRHolderQueryServiceClassSoap", Namespace="http://www.iru.org")]
    public partial class SafeTIRHolderQueryServiceClass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSTCHQOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SafeTIRHolderQueryServiceClass() {
            this.Url = global::RTSTestClient.Properties.Settings.Default.RTSTestClient_Query_SafeTIRHolderQueryServiceClass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSTCHQCompletedEventHandler WSTCHQCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.iru.org/WSTCHQ", RequestNamespace="http://www.iru.org", ResponseNamespace="http://www.iru.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TIRHolderResponse WSTCHQ(TIRHolderQuery su) {
            object[] results = this.Invoke("WSTCHQ", new object[] {
                        su});
            return ((TIRHolderResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWSTCHQ(TIRHolderQuery su, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WSTCHQ", new object[] {
                        su}, callback, asyncState);
        }
        
        /// <remarks/>
        public TIRHolderResponse EndWSTCHQ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TIRHolderResponse)(results[0]));
        }
        
        /// <remarks/>
        public void WSTCHQAsync(TIRHolderQuery su) {
            this.WSTCHQAsync(su, null);
        }
        
        /// <remarks/>
        public void WSTCHQAsync(TIRHolderQuery su, object userState) {
            if ((this.WSTCHQOperationCompleted == null)) {
                this.WSTCHQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSTCHQOperationCompleted);
            }
            this.InvokeAsync("WSTCHQ", new object[] {
                        su}, this.WSTCHQOperationCompleted, userState);
        }
        
        private void OnWSTCHQOperationCompleted(object arg) {
            if ((this.WSTCHQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSTCHQCompleted(this, new WSTCHQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
    public partial class TIRHolderQuery {
        
        private string subscriberIDField;
        
        private string messageTagField;
        
        private byte[] eSessionKeyField;
        
        private byte[] tIRCarnetHolderQueryParamsField;
        
        private string query_IDField;
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        public string MessageTag {
            get {
                return this.messageTagField;
            }
            set {
                this.messageTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ESessionKey {
            get {
                return this.eSessionKeyField;
            }
            set {
                this.eSessionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] TIRCarnetHolderQueryParams {
            get {
                return this.tIRCarnetHolderQueryParamsField;
            }
            set {
                this.tIRCarnetHolderQueryParamsField = value;
            }
        }
        
        /// <remarks/>
        public string Query_ID {
            get {
                return this.query_IDField;
            }
            set {
                this.query_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
    public partial class TIRHolderResponse {
        
        private string messageTagField;
        
        private byte[] eSessionKeyField;
        
        private byte[] tIRCarnetHolderResponseParamsField;
        
        private int returnCodeField;
        
        private string query_IDField;
        
        /// <remarks/>
        public string MessageTag {
            get {
                return this.messageTagField;
            }
            set {
                this.messageTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ESessionKey {
            get {
                return this.eSessionKeyField;
            }
            set {
                this.eSessionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] TIRCarnetHolderResponseParams {
            get {
                return this.tIRCarnetHolderResponseParamsField;
            }
            set {
                this.tIRCarnetHolderResponseParamsField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Query_ID {
            get {
                return this.query_IDField;
            }
            set {
                this.query_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void WSTCHQCompletedEventHandler(object sender, WSTCHQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSTCHQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSTCHQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TIRHolderResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TIRHolderResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591