//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5472.
// 
#pragma warning disable 1591

namespace RTSTestClient.WSRQ {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReconciliationQueryServiceClassSoap", Namespace="http://www.iru.org")]
    public partial class ReconciliationQueryServiceClass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSRQOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReconciliationQueryServiceClass() {
            this.Url = global::RTSTestClient.Properties.Settings.Default.RTSTestClient_WSRQ_ReconciliationQueryServiceClass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSRQCompletedEventHandler WSRQCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.iru.org/WSRQ", RequestNamespace="http://www.iru.org", ResponseNamespace="http://www.iru.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReconciliationResponse WSRQ(ReconciliationQuery su) {
            object[] results = this.Invoke("WSRQ", new object[] {
                        su});
            return ((ReconciliationResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWSRQ(ReconciliationQuery su, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WSRQ", new object[] {
                        su}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReconciliationResponse EndWSRQ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReconciliationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void WSRQAsync(ReconciliationQuery su) {
            this.WSRQAsync(su, null);
        }
        
        /// <remarks/>
        public void WSRQAsync(ReconciliationQuery su, object userState) {
            if ((this.WSRQOperationCompleted == null)) {
                this.WSRQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSRQOperationCompleted);
            }
            this.InvokeAsync("WSRQ", new object[] {
                        su}, this.WSRQOperationCompleted, userState);
        }
        
        private void OnWSRQOperationCompleted(object arg) {
            if ((this.WSRQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSRQCompleted(this, new WSRQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
    public partial class ReconciliationQuery {
        
        private string messageTagField;
        
        private string subscriberIDField;
        
        private byte[] eSessionKeyField;
        
        private byte[] reconciliationQueryDataField;
        
        private string sender_MessageIDField;
        
        private string information_Exchange_VersionField;
        
        /// <remarks/>
        public string MessageTag {
            get {
                return this.messageTagField;
            }
            set {
                this.messageTagField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ESessionKey {
            get {
                return this.eSessionKeyField;
            }
            set {
                this.eSessionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ReconciliationQueryData {
            get {
                return this.reconciliationQueryDataField;
            }
            set {
                this.reconciliationQueryDataField = value;
            }
        }
        
        /// <remarks/>
        public string Sender_MessageID {
            get {
                return this.sender_MessageIDField;
            }
            set {
                this.sender_MessageIDField = value;
            }
        }
        
        /// <remarks/>
        public string Information_Exchange_Version {
            get {
                return this.information_Exchange_VersionField;
            }
            set {
                this.information_Exchange_VersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iru.org")]
    public partial class ReconciliationResponse {
        
        private string senderField;
        
        private string messageTagField;
        
        private byte[] eSessionKeyField;
        
        private byte[] reconciliationRequestDataField;
        
        private string sender_MessageIDField;
        
        private int returnCodeField;
        
        /// <remarks/>
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public string MessageTag {
            get {
                return this.messageTagField;
            }
            set {
                this.messageTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ESessionKey {
            get {
                return this.eSessionKeyField;
            }
            set {
                this.eSessionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ReconciliationRequestData {
            get {
                return this.reconciliationRequestDataField;
            }
            set {
                this.reconciliationRequestDataField = value;
            }
        }
        
        /// <remarks/>
        public string Sender_MessageID {
            get {
                return this.sender_MessageIDField;
            }
            set {
                this.sender_MessageIDField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void WSRQCompletedEventHandler(object sender, WSRQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSRQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSRQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReconciliationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReconciliationResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591