//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTSTestClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetReadOnly {
            get {
                return ((bool)(this["SetReadOnly"]));
            }
            set {
                this["SetReadOnly"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/SMDWebs/RTS/TCHQ_WS/tirCarnetQuery.asmx")]
        public string RTSTestClient_Query_SafeTIRHolderQueryServiceClass {
            get {
                return ((string)(this["RTSTestClient_Query_SafeTIRHolderQueryServiceClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/SMDWebs/RTS/WSRQ_WS/WSRQ.asmx")]
        public string RTSTestClient_WSRQ_ReconciliationQueryServiceClass {
            get {
                return ((string)(this["RTSTestClient_WSRQ_ReconciliationQueryServiceClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/SMDWebs/RTS/WSST_WS/safetirupload.asmx")]
        public string RTSTestClient_WSRE_SafeTirUpload {
            get {
                return ((string)(this["RTSTestClient_WSRE_SafeTirUpload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/SMDWebs/RTS/WSST_WS/safetirupload.asmx")]
        public string RTSTestClient_WSST_SafeTirUpload {
            get {
                return ((string)(this["RTSTestClient_WSST_SafeTirUpload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/SMDWEBS/EPD/TIREPDG2B/TIREPDG2BService.asmx")]
        public string RTSTestClient_TIREPDG2B_TIREPDG2BService {
            get {
                return ((string)(this["RTSTestClient_TIREPDG2B_TIREPDG2BService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/SMDWEBS/EPD/TIREPDB2GService.asmx")]
        public string RTSTestClient_TIREPDB2G_TIREPDB2GServiceClass {
            get {
                return ((string)(this["RTSTestClient_TIREPDB2G_TIREPDB2GServiceClass"]));
            }
        }
    }
}
